# Generated by Django 3.1.3 on 2021-08-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgroup', '0002_chatgroup_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='chat_group_name'),
        ),
    ]
