# Generated by Django 3.1.3 on 2021-08-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatgroup', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('message_text', models.TextField(default='dummy text')),
                ('chat_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_group_messages', to='chatgroup.chatgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='members.groupmember')),
            ],
        ),
    ]
