# Generated by Django 3.1.3 on 2021-08-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.TextField(choices=[('LEFT', 'left'), ('JOINED', 'added'), ('CHANGED_CONTACT', 'changed their phone number'), ('INVITED', 'INVITED'), ('REMOVED', 'REMOVED'), ('GROUP_CREATED', 'created group')], default='joined')),
                ('event_date', models.DateTimeField(verbose_name='event_date')),
                ('chat_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_group_events', to='chatgroup.chatgroup')),
            ],
        ),
    ]
