# Generated by Django 3.2.5 on 2021-08-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('group_name', models.CharField(max_length=150, unique=True)),
                ('datetime_created', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppChatFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('google_id', models.CharField(max_length=100, unique=True)),
                ('web_content_link', models.CharField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('datetime_created', models.DateTimeField()),
                ('filesize', models.SmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyser.whatsappgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
