# Generated by Django 3.2.5 on 2021-08-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_whatsappchatfile_whatsappgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchatfile',
            name='status',
            field=models.CharField(blank=True, choices=[('processed', 'Processed'), ('pending', 'Pending'), ('failed', 'Failed Processing'), ('to_reprocess', 'Reprocess')], max_length=20, null=True),
        ),
    ]
