# Generated by Django 3.2.5 on 2021-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0003_whatsappchatfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappchatfile',
            name='filesize',
            field=models.IntegerField(),
        ),
    ]
