# Generated by Django 3.2.5 on 2021-08-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0004_alter_whatsappchatfile_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappchatfile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='analyser.whatsappgroup'),
        ),
    ]
