# Generated by Django 3.2.5 on 2021-08-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0005_alter_whatsappchatfile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchatfile',
            name='comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
