# Generated by Django 3.2.5 on 2021-08-04 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0006_whatsappchatfile_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappchatfile',
            name='status',
            field=models.CharField(blank=True, choices=[('processed', 'Processed'), ('pending', 'Pending'), ('failed', 'Failed Processing'), ('failed_preprocessing', 'Failed Pre Processing'), ('to_reprocess', 'Reprocess')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserDailyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('name_phone', models.CharField(max_length=100)),
                ('stats_date', models.DateField()),
                ('most_active_hr', models.SmallIntegerField(default=-1)),
                ('popular_emoji', models.CharField(blank=True, max_length=15, null=True)),
                ('no_messages', models.SmallIntegerField()),
                ('no_images', models.SmallIntegerField()),
                ('no_links', models.SmallIntegerField()),
                ('no_emojis', models.SmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyser.whatsappgroup')),
            ],
            options={
                'unique_together': {('name_phone', 'group', 'stats_date')},
            },
        ),
        migrations.CreateModel(
            name='GroupDailyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('stats_date', models.DateField()),
                ('new_users', models.SmallIntegerField()),
                ('left_users', models.SmallIntegerField()),
                ('most_active_hr', models.SmallIntegerField(default=-1)),
                ('popular_emoji', models.CharField(blank=True, max_length=15, null=True)),
                ('no_messages', models.SmallIntegerField()),
                ('no_images', models.SmallIntegerField()),
                ('no_links', models.SmallIntegerField()),
                ('no_emojis', models.SmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyser.whatsappgroup')),
            ],
            options={
                'unique_together': {('group', 'stats_date')},
            },
        ),
    ]
