# Generated by Django 3.2.5 on 2021-08-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0008_messagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappgroup',
            name='group_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
