# Generated by Django 3.2.5 on 2021-08-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0009_alter_whatsappgroup_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNameChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateField()),
                ('from_name', models.CharField(max_length=150)),
                ('to_name', models.CharField(max_length=150)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyser.whatsappgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
