# Generated by Django 3.2.5 on 2021-08-10 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0010_groupnamechanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdailystats',
            name='chat_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='analyser.whatsappchatfile'),
            preserve_default=False,
        ),
    ]
