# Generated by Django 3.2.5 on 2021-08-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0011_groupdailystats_chat_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdailystats',
            name='popular_emoji',
        ),
        migrations.RemoveField(
            model_name='userdailystats',
            name='popular_emoji',
        ),
        migrations.AddField(
            model_name='groupdailystats',
            name='emojis',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='userdailystats',
            name='emojis',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
