# Generated by Django 3.2.5 on 2021-08-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0014_messagelog_chat_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupnamechanges',
            name='change_date',
        ),
        migrations.AddField(
            model_name='groupnamechanges',
            name='change_datetime',
            field=models.DateTimeField(default='1970-01-01 00:00:00+03:00'),
            preserve_default=False,
        ),
    ]
