# Generated by Django 3.2.5 on 2021-08-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0016_alter_messagelog_chat_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='r_user', to='analyser.userdailystats'),
        ),
    ]
