# Generated by Django 3.2.5 on 2021-08-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0017_alter_messagelog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappchatfile',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
