# Generated by Django 3.2.5 on 2021-09-26 21:04

from django.db import models, migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'Business Counselor'),
        Group(name=u'Business Advisor'),
        Group(name=u'Program Manager'),
        Group(name=u'Administrator'),
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'Business Counselor',
            u'Business Advisor',
            u'Program Manager',
            u'Administrator',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0018_alter_whatsappchatfile_title'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]

