# Generated by Django 3.2.5 on 2021-10-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0018_alter_whatsappchatfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='designation',
            field=models.CharField(blank=True, choices=[('data_manager', 'Data Manager'), ('system_admin', 'System Administrator'), ('business_counselor', 'Business Counselor'), ('business_advisor', 'Business Advisor'), ('program_manager', 'Program Manager')], max_length=20, null=True),
        ),
    ]
