# Generated by Django 3.2.5 on 2021-10-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0021_auto_20211010_2015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advisormanagerassignment',
            unique_together={('manager', 'advisor')},
        ),
        migrations.AlterUniqueTogether(
            name='counseloradvisorassignment',
            unique_together={('counselor', 'advisor')},
        ),
    ]
