# Generated by Django 3.2.5 on 2021-11-26 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0022_auto_20211010_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorAdvisorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='r_counselor_group', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='r_group_counselor', to='analyser.whatsappgroup')),
            ],
            options={
                'unique_together': {('counselor', 'group')},
            },
        ),
    ]
