image: docker:latest

stages:
  - build

variables:
  DOCKER_DRIVER: overlay
  DOCKER_USER: dockerci

services:
  - docker:dind

before_script:
  # add gdal ppa repositories

job:
  stage: build
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --pull -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
