# Generated by Django 3.1.3 on 2021-08-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='group_member_username')),
                ('messages', models.IntegerField(null=True)),
                ('words', models.IntegerField(null=True)),
                ('emojis', models.TextField(null=True)),
                ('media', models.TextField(null=True)),
                ('links', models.TextField(null=True)),
                ('top_emojis', models.TextField(null=True)),
                ('top_words', models.TextField(null=True)),
                ('top_links', models.TextField(null=True)),
                ('date_joined', models.DateTimeField(null=True)),
                ('is_group_admin', models.BooleanField(default=False, null=True)),
                ('chat_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_group_members', to='chatgroup.chatgroup')),
            ],
        ),
    ]
