# Generated by Django 3.1.3 on 2021-08-04 21:31

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_file_name', models.CharField(blank=True, max_length=1000)),
                ('chat_txt_file', models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='mspark-test-folder', verbose_name='chat_txt_file')),
                ('date_uploaded', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatUploadDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_file_link', models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='mspark-test-folder', verbose_name='members_file_link')),
                ('events_file_link', models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='mspark-test-folder', verbose_name='events_file_link')),
                ('messages_file_link', models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='mspark-test-folder', verbose_name='messages_file_link')),
                ('most_popular_emojis', models.CharField(max_length=1000, null=True)),
                ('most_active_days', models.CharField(max_length=1000, null=True)),
                ('most_active_members', models.CharField(max_length=1000, null=True)),
                ('joined', models.CharField(max_length=1000, null=True)),
                ('left', models.CharField(max_length=1000, null=True)),
                ('most_active_time', models.CharField(max_length=1000, null=True)),
                ('messages', models.IntegerField(default=0, null=True)),
                ('media', models.IntegerField(default=0, null=True)),
                ('emojis', models.IntegerField(default=0, null=True)),
                ('links', models.IntegerField(default=0, null=True)),
                ('chat_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_upload_group', to='chatgroup.chatgroup')),
                ('chat_upload', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_file_details', to='uploads.chatupload')),
            ],
        ),
    ]
