# Generated by Django 3.1.3 on 2021-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_chatupload_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatupload',
            name='is_analysed',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes'), ('ANALYSING', 'Analysing')], default='NO', max_length=255),
        ),
    ]
